### ISSUE TITLE
can't run GinanEDA

### ISSUE THREAD

**Issue by Ali-Fallahi** [GeoscienceAustralia/ginan#131]
Hey, dear Ginan support.
I installed Ginan using docker in Windows with this docker-compose(my docker desktop use wsl to run):
```
version: '3.8'

services:
  ginan:
    image: gnssanalysis/ginan:v3.0.0
    container_name: ginan_container
    ports:
      - "5000:5000"
    volumes:
      - input_data:/ginan/inputData/data
      - input_products:/ginan/inputData/products
      - gnss_outputs:/data
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  input_data:
  input_products:
  gnss_outputs:
  mongo_data:
```
I can not connect to MongoDB like that!
so I successfully downloaded example inputs and also ran MongoDB in the background using these codes:
```
mkdir -p /var/log/mongodb
touch /var/log/mongodb/mongod.log
chmod -R 755 /var/log/mongodb

mkdir -p /data/db/path
chown -R mongodb:mongodb /data/db/path

mongod --dbpath /data/db --logpath /var/log/mongodb/mongod.log --fork --bind_ip 127.0.0.1 --port 27017
```

after all of that I ran pea --config ppp_example.yaml and successfully got all trace files and GPS files

now I want to run GinanEDA but unfortunately, it does not appear in my browser(I use localhost).
I run the index.py and this code appears:
root@b7d249c42820:/ginan/scripts/GinanEDA# python3 index.py 
Serving Flask app 'index'
Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
Running on http://127.0.0.1:5000
Press CTRL+C to quit

my main problem is all of the ports in Ginan are not accessible on my localhost
