### ISSUE TITLE
How to specify the approximated log start time for RTCM file?

### ISSUE THREAD

**Issue by whu-dyf** [GeoscienceAustralia/ginan#50]
Dear Ginan team,

I want to run simulated real-time PPP using the recoded .rtcm3 files. Is there any options to specify the approximated log start time in the configuration?  Thank you in advance for your reply!

**Comment by polytopes-design** [comment]
These options may specify the start and end epochs for processing, however if they are undefined the software will automatically start at the first epoch found in the rtcm/rinex file.

```yaml
processing_options:

    epoch_control:
        start_epoch:                2019-07-17 01:00:00
        end_epoch:                  2019-07-19 23:00:00
        ```
